package ru.stqa.ptf.addressbook.tests;// Generated by Selenium IDE


import org.openqa.selenium.chrome.ChromeDriver;

import org.testng.annotations.Test;

public class GroupDeletionTests extends TestBase {
    private ChromeDriver wd;

    @Test
    public void testGroupDeletion() {
        app.gotoGroupPage();
        app.selectGroup();
        app.deleteSelectedGroups();
        app.returnToGroupPage();
    }

}
