package ru.stqa.ptf.addressbook;// Generated by Selenium IDE


import org.openqa.selenium.chrome.ChromeDriver;

import org.testng.annotations.Test;

public class GroupDeletionTests extends TestBase {
    private ChromeDriver wd;

    @Test
    public void testGroupDeletion() {
        gotoGroupPage();
        selectGroup();
        deleteSelectedGroups();
        returnToGroupPage();
    }

}
